version: "3"

services:

  db:
    container_name: 'database'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo

  dockerapi:
    build: ./api
    ports:
      - "3001:3001"
    
  dockerweb:
    build: ./web
    ports:
      - "8080:8080"
